version: '3'
services:

  dash_zset:
    build:
      context: .
      dockerfile: DockerComs/Dockerfile
    image: dashrob:v1
    command: python data_zset.py
    network_mode: host

  dash_zset_dash:
    build:
      context: .
      dockerfile: DockerComs/Dockerfile
    image: dashrob:v1
    command: python data_zset_dash.py
    network_mode: host