version: '3'
services:

  dash_zset:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPO=dashrob
        - TAG=v1
    image: ${REPO}:${TAG}
    command: python data_zset.py
    network_mode: host

  dash_zset_dash:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REPO=dashrob
        - TAG=v1
    image: ${REPO}:${TAG}
    command: python data_zset_dash.py
    network_mode: host